//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogAndPeoples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caes_Dono
    {
        public int Id { get; set; }
        public int Id_dono { get; set; }
        public int Id_cao { get; set; }
    
        public virtual Caes Caes { get; set; }
        public virtual Donos Donos { get; set; }
    }
}
